version: '3'

services:
  devapp:
    restart: always
    image: 'ambientum/php:7.3-nginx'
    volumes:
      - './:/var/www/app'
      - '${HOME}/.composer/:/home/ambientum/.composer/'
    ports:
      - '8081:8080'
